name: unseen
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - affine=2.4.0
  - aiohttp=3.9.5
  - aiosignal=1.3.1
  - alsa-lib=1.2.12
  - ansicolors=1.1.8
  - appdirs=1.4.4
  - asciitree=0.3.3
  - asttokens=2.4.1
  - attr=2.5.1
  - attrs=24.2.0
  - aws-c-auth=0.7.25
  - aws-c-cal=0.7.3
  - aws-c-common=0.9.25
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.7
  - aws-c-io=0.14.18
  - aws-c-mqtt=0.10.4
  - aws-c-s3=0.6.4
  - aws-c-sdkutils=0.1.19
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.27.5
  - aws-sdk-cpp=1.11.379
  - azure-core-cpp=1.13.0
  - azure-identity-cpp=1.8.0
  - azure-storage-blobs-cpp=12.12.0
  - azure-storage-common-cpp=12.7.0
  - azure-storage-files-datalake-cpp=12.11.0
  - blosc=1.21.6
  - bokeh=3.5.1
  - boltons=24.0.0
  - bottleneck=1.4.2
  - branca=0.7.2
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.33.0
  - ca-certificates=2025.1.31
  - cairo=1.18.0
  - cartopy=0.23.0
  - certifi=2025.1.31
  - cf_xarray=0.9.4
  - cffi=1.17.0
  - cfgv=3.3.1
  - cfitsio=4.4.1
  - cftime=1.6.3
  - charset-normalizer=3.3.2
  - click=8.1.7
  - click-plugins=1.1.1
  - cligj=0.7.2
  - cloudpickle=3.0.0
  - cmaps=2.0.1
  - cmdline_provenance=1.1.0
  - cmocean=4.0.3
  - colorama=0.4.6
  - colorspacious=1.1.2
  - comm=0.2.2
  - contourpy=1.2.1
  - cycler=0.12.1
  - cytoolz=0.12.3
  - dask=2025.2.0
  - dask-core=2025.2.0
  - dask-expr=2.0.0
  - dask-jobqueue=0.8.5
  - dbus=1.13.6
  - debugpy=1.8.5
  - decorator=5.1.1
  - distlib=0.3.8
  - distributed=2025.2.0
  - docopt-ng=0.9.0
  - entrypoints=0.4
  - esmf=8.6.1
  - esmpy=8.6.1
  - exceptiongroup=1.2.2
  - executing=2.0.1
  - expat=2.6.2
  - fasteners=0.17.3
  - filelock=3.15.4
  - fiona=1.9.6
  - flexcache=0.3
  - flexparser=0.3.1
  - flox=0.9.8
  - fmt=11.0.2
  - folium=0.17.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.53.1
  - freetype=2.12.1
  - freexl=2.0.0
  - frozenlist=1.5.0
  - fsspec=2024.6.1
  - gdal=3.9.1
  - geopandas=0.14.2
  - geopandas-base=0.14.2
  - geos=3.12.2
  - geotiff=1.7.3
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - gflags=2.2.2
  - giflib=5.2.2
  - gitdb=4.0.11
  - gitpython=3.1.43
  - glib=2.80.3
  - glib-tools=2.80.3
  - glog=0.7.1
  - graphite2=1.3.13
  - gst-plugins-base=1.24.6
  - gstreamer=1.24.6
  - h2=4.1.0
  - harfbuzz=9.0.0
  - hdf4=4.2.15
  - hdf5=1.14.3
  - hpack=4.0.0
  - hyperframe=6.0.1
  - icu=73.2
  - identify=2.6.0
  - idna=3.7
  - importlib-metadata=8.2.0
  - importlib_metadata=8.2.0
  - importlib_resources=6.4.5
  - iniconfig=2.0.0
  - ipykernel=6.29.5
  - ipynbname=2023.2.0.0
  - ipython=8.26.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - joblib=1.4.2
  - json-c=0.17
  - jsonpickle=3.2.2
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - kealib=1.5.3
  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - legacy-cgi=2.6.2
  - lerc=4.0.0
  - libabseil=20240116.2
  - libaec=1.1.3
  - libarchive=3.7.4
  - libarrow=17.0.0
  - libarrow-acero=17.0.0
  - libarrow-dataset=17.0.0
  - libarrow-substrait=17.0.0
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.69
  - libcblas=3.9.0
  - libclang-cpp15=15.0.7
  - libclang13=18.1.8
  - libcrc32c=1.1.2
  - libcups=2.3.3
  - libcurl=8.9.1
  - libdeflate=1.21
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.2
  - libffi=3.4.2
  - libflac=1.4.3
  - libgcc=14.1.0
  - libgcc-ng=14.1.0
  - libgcrypt=1.11.0
  - libgdal=3.9.1
  - libgdal-core=3.9.1
  - libgdal-fits=3.9.1
  - libgdal-grib=3.9.1
  - libgdal-hdf4=3.9.1
  - libgdal-hdf5=3.9.1
  - libgdal-jp2openjpeg=3.9.1
  - libgdal-kea=3.9.1
  - libgdal-netcdf=3.9.1
  - libgdal-pdf=3.9.1
  - libgdal-pg=3.9.1
  - libgdal-postgisraster=3.9.1
  - libgdal-tiledb=3.9.1
  - libgdal-xls=3.9.1
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran=3.0.0
  - libgfortran-ng=14.1.0
  - libgfortran5=14.1.0
  - libglib=2.80.3
  - libgomp=14.1.0
  - libgoogle-cloud=2.28.0
  - libgoogle-cloud-storage=2.28.0
  - libgpg-error=1.50
  - libgrpc=1.62.2
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - libkml=1.3.0
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libllvm15=15.0.7
  - libllvm18=18.1.8
  - libnetcdf=4.9.2
  - libnghttp2=1.58.0
  - libnsl=2.0.1
  - libogg=1.3.5
  - libopenblas=0.3.27
  - libopus=1.3.1
  - libparquet=17.0.0
  - libpnetcdf=1.13.0
  - libpng=1.6.43
  - libpq=16.4
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - librttopo=1.1.0
  - libsndfile=1.2.2
  - libsodium=1.0.18
  - libspatialindex=2.0.0
  - libspatialite=5.1.0
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libstdcxx=14.1.0
  - libstdcxx-ng=14.1.0
  - libsystemd0=255
  - libthrift=0.20.0
  - libtiff=4.6.0
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libvorbis=1.3.7
  - libwebp-base=1.4.0
  - libxcb=1.16
  - libxcrypt=4.4.36
  - libxkbcommon=1.7.0
  - libxml2=2.12.7
  - libzip=1.10.1
  - libzlib=1.3.1
  - llvmlite=0.44.0
  - lmoments3=1.0.7
  - locket=1.0.0
  - lz4=4.3.3
  - lz4-c=1.9.4
  - lzo=2.10
  - mapclassify=2.8.0
  - markupsafe=2.1.5
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.7
  - minizip=4.0.7
  - mpg123=1.32.6
  - mpi=1.0
  - mpich=4.2.2
  - msgpack-python=1.0.8
  - multidict=6.1.0
  - munkres=1.1.4
  - mysql-common=8.3.0
  - mysql-libs=8.3.0
  - nbclient=0.10.0
  - nbformat=5.10.4
  - nc-time-axis=1.4.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - netcdf-fortran=4.6.1
  - netcdf4=1.7.1
  - networkx=3.3
  - nodeenv=1.9.1
  - nspr=4.35
  - nss=3.103
  - numba=0.61.0
  - numcodecs=0.12.1
  - numpy=2.0.2
  - numpy_groupies=0.11.2
  - openjpeg=2.5.2
  - openssl=3.4.1
  - orc=2.0.1
  - packaging=24.1
  - pandas=2.2.3
  - papermill=2.6.0
  - parallelio=2.6.2
  - parso=0.8.4
  - partd=1.4.2
  - patsy=0.5.6
  - pcre2=10.44
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pint=0.24.3
  - pip=24.0
  - pixman=0.43.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.2.2
  - pluggy=1.5.0
  - ply=3.11
  - pooch=1.8.2
  - poppler=24.08.0
  - poppler-data=0.4.12
  - postgresql=16.4
  - pre-commit=3.7.1
  - proj=9.4.1
  - prompt-toolkit=3.0.47
  - propcache=0.2.0
  - properscoring=0.1
  - psutil=6.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulseaudio-client=17.0
  - pure_eval=0.2.3
  - pyarrow=17.0.0
  - pyarrow-core=17.0.0
  - pyarrow-hotfix=0.6
  - pycparser=2.22
  - pydap=3.5.3
  - pygments=2.18.0
  - pyparsing=3.1.2
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - pyshp=2.3.1
  - pysocks=1.7.1
  - pytest=8.2.2
  - python=3.11.9
  - python-dateutil=2.9.0
  - python-fastjsonschema=2.20.0
  - python-tzdata=2024.1
  - python_abi=3.11
  - pytz=2024.1
  - pyyaml=6.0.2
  - pyzmq=26.1.0
  - qhull=2020.2
  - qt-main=5.15.8
  - rasterio=1.3.10
  - re2=2023.09.01
  - readline=8.2
  - referencing=0.35.1
  - regionmask=0.12.1
  - requests=2.32.3
  - rpds-py=0.20.1
  - rtree=1.3.0
  - s2n=1.5.0
  - scikit-learn=1.5.1
  - scipy=1.15.2
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=72.1.0
  - shapely=2.0.5
  - sip=6.7.12
  - six=1.16.0
  - smmap=5.0.0
  - snappy=1.2.1
  - snuggs=1.4.7
  - sortedcontainers=2.4.0
  - sparse=0.15.4
  - spdlog=1.14.1
  - sqlite=3.46.0
  - stack_data=0.6.2
  - statsmodels=0.14.2
  - tblib=3.0.0
  - tenacity=9.0.0
  - threadpoolctl=3.5.0
  - tiledb=2.25.0
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.0.1
  - toolz=0.12.1
  - tornado=6.4.1
  - tqdm=4.66.6
  - traitlets=5.14.3
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzcode=2024a
  - tzdata=2024a
  - ukkonen=1.0.1
  - uriparser=0.9.8
  - urllib3=2.2.2
  - virtualenv=20.26.3
  - wcwidth=0.2.13
  - webob=1.8.9
  - wheel=0.44.0
  - xarray=2025.1.2
  - xarray-datatree=0.0.14
  - xcb-util=0.4.1
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xclim=0.49.0
  - xerces-c=3.2.5
  - xesmf=0.8.7
  - xhistogram=0.3.2
  - xkeyboard-config=2.42
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.11
  - xorg-libxxf86vm=1.1.5
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xf86vidmodeproto=2.3.1
  - xorg-xproto=7.0.31
  - xskillscore=0.0.26
  - xyzservices=2024.6.0
  - xz=5.2.6
  - yamale=5.2.1
  - yaml=0.2.5
  - yarl=1.16.0
  - zarr=2.18.2
  - zeromq=4.3.5
  - zict=3.0.0
  - zipp=3.20.0
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - coverage==7.3.2
      - pyproj==3.7.1
      - pytest-cov==4.1.0
      - xstatstests==0.0.3
